name: Booking Bot

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          PROXY_1: ${{ secrets.PROXY_1 }}
          PROXY_2: ${{ secrets.PROXY_2 }}
          PROXY_3: ${{ secrets.PROXY_3 }}
        run: python tracker.py
