name: Test Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run Telegram test
        run: python test_telegram.py
