name: Test Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install requests

      # Run Telegram test script
      - name: Run Telegram test
        run: python test_telegram.py
